### ISSUE TITLE
https://digitaljunky.io not accessible?

### ISSUE THREAD

**Issue by adityagaykar** [amatelin/IoT.me#4]
Can you provide a mirror to access the tutorial for this repo? Or a github.io page may be?

**Comment by icebob** [comment]
In archive: http://web.archive.org/web/20170220111105/http://digitaljunky.io/make-your-own-data-platform-for-the-internet-of-things-using-node-js-and-express-js

**Comment by amatelin** [comment]
Sorry I'm on a bicycle somewhere in Bangladesh and I just realized that my hosting service broke the .htaccess file after migrating their servers. It's fixed now.
